# pre-commit workflow
#
# Ensures the codebase passes the pre-commit stack.
# We run this on GHA to catch issues in commits from contributors who haven't
# set up pre-commit.

name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
